---
- hosts: all
  gather_facts: no

  tasks:
  - name: Check the date on the server.
    command: date
  - name: Check the ens192 ip on the server.
    command: ifconfig ens192
  - name: Check the route on the server.
    command: route -n

